name       : perl-file-sharedir-install
version    : 0.11
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/File-ShareDir-Install-0.11.tar.gz : 32bf8772e9fea60866074b27ff31ab5bc3f88972d61915e84cbbb98455e00cc8
license    : Artistic-2.0
component  : programming.perl
summary    : Install read-only date files from Perl
description: |
    File::ShareDir::Install allows you to install read-only data files from a distribution. It is a companion module to File::ShareDir, which allows you to locate these files after installation.
builddeps  :
    - perl-module-build
rundeps    :
    - perl-file-sharedir
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
